In [1]:
%matplotlib inline

# NLTK 자연어 처리 패키지

- 샘플 코퍼스 = 말뭉치

### 말뭉치
- 전처리를 위해 training 시기기위한 데이터
- gutenberg : 너무 오래되서 저작권이 말세된 글들
- tagging이 되있어야지 분석이 가능함 => 처음에 사람이 일일이 다 해줘야함

### 토큰 생성
- 사람이 이해하는 뜻을 가진 어떤 단위로 쪼갬
- 이러한 작업을 tokenizing이라 부름 그렇게 해주는 함수를 tokenizer
- sent_tokenize는 마침표가 나와서 문장이 끝났다라고 나올때 끈음
- word_tokenize는 단어 단위로 끈음(구두점, 띄어쓰기)
- RegexpTokenizer는 어떤 형태를 가진애들만 토큰으로 인정한다.

### 형태소 분석 (토큰이 잘되야지)
- 

### 어간 추출과 원형 복원
- 간단하지 않음
- 초기에는 s가 붙거나d가 붙었을 때 하나로 묶는 방법은 없을까? => 스태밍
    - 어간 추출 (어미를 끈어버림)
    - live lives 에서 s 만 빼버린다 등
- PorterStemmer : es를 없에 버렸음
- LancasterStemmer : 여기서도 es없음
- 여기서 토큰은 liv나 die 같은 것들인데 이것들은 의미가 없음! 우리가 지정해주는 거야
- 원형 복원(lemmatizing) : 워드넷이라고 부르는 인터넷 사전임 단순하게 뭐는 뭐라고 되있는 사전이아니고 같은 컨셉을 가진 단어를 묶어놨음(단어의 네트웤) 그래서 이미 머신러닝이 되있는 애들임 ex) 개, 고양이 = 동물

### POS tagging (token이 잘 되도록)
- 품사 추가 : 이단어는 명사다 동사다 등
- 찾아서 옆에 튜플로 붙여놓음
- 품사의 세부적인 명칭들이 있음
- 문법학자마다 품사를 정의하기가 다름
- 한국어도 잘 정의가 안되있음
- 우리가 표준이라고 하는 것은 21c 세종 계획
- 태깅되있는 것을 하나로 붙여서 토큰화 시킴
- 영어는 같은 단어인데 품사가 다른 경우가 많아서 이렇게 함
    - ex) "ship"  배 = N / 실어나르다 = V
- ex) "volume/NN" 이렇게 토큰

In [2]:
import nltk

nltk.download('averaged_perceptron_tagger')
nltk.download("gutenberg")
nltk.download('punkt')
nltk.download('reuters')
nltk.download("stopwords")
nltk.download("webtext")
nltk.download("wordnet")

In [3]:
nltk.corpus.gutenberg.fileids()

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

In [8]:
from nltk.tokenize import sent_tokenize
print(sent_tokenize(emma_raw[:1000])[3])

Sixteen years had Miss Taylor been in Mr. Woodhouse's family,
less as a governess than a friend, very fond of both daughters,
but particularly of Emma.


In [9]:
from nltk.tokenize import word_tokenize
word_tokenize(emma_raw[50:100])

['Emma',
 'Woodhouse',
 ',',
 'handsome',
 ',',
 'clever',
 ',',
 'and',
 'rich',
 ',',
 'with',
 'a']

In [10]:
from nltk.tokenize import RegexpTokenizer
t = RegexpTokenizer("[\w]+")
t.tokenize(emma_raw[50:100])

['Emma', 'Woodhouse', 'handsome', 'clever', 'and', 'rich', 'with', 'a']

# KoNLPy 한국어 처리 패키지

- 자체적으로 무엇인가를 하는 것이 아니고 구성되어있는 처리패키지를 모아놓은 것임
- 꼬꼬마, 한나눔, Twiiter, Mecab(원래 일본어용인데 문법이 유사해서 한국어로 트레이닝), Komoran
- 깔아서 할때 주의할점: 파이썬이나 자바를 연동해야함

### 한국어 말뭉치
- corpus라고 되있는데 별거 없고 그냥 흉내만 냈음
- 실제로 뭘하기에는 양이 너무적음, 그냥 샘플이라고 생각

### 형태소 분석
- 5가지의 형태소 분석기를 묶어놨음
- morphs , nouns , pos(튜플로!)

##### 명사 추출
- 명사만 뽑아라!
- 근대 같은 명령도 분석기 마다 다르게 나옴
- 대학원에서 학생들이 만든것이고 만든것도 20년전거임
- 제대로된 트레이닝 데이터가 있어야함 근대 제대로된 라벨링이 된것이 없음
- 누군가 돈을 대줘서 고급인력을 써서 해야되는데 그런 돈을 대줄 사람이 없음
- kkma : 대한, 대한민국, 대한민국헌법 이렇게 쪼개는 것! =엔브램

##### 형태소 추출
- morphs
- 세부적으로 다쪼갬
- 형태소 분석기마다 결과가 다름

##### 품사 부착
- pos : 단어하나하나를 튜플로 만들어줌
- ('대한민국', 'NNG')

In [19]:
from konlpy.corpus import kolaw
kolaw.fileids()
c = kolaw.open('constitution.txt').read()
print(c[:66])

대한민국헌법

유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로 건립된 대한민국임시정부의 법통과 불의에 항거한


In [14]:
from konlpy.tag import *
hannanum = Hannanum()
kkma = Kkma()
twitter = Twitter()

In [20]:
kkma.nouns(c[:66])

['대한',
 '대한민국',
 '대한민국헌법',
 '민국',
 '헌법',
 '유구',
 '역사',
 '전통',
 '우리',
 '국민',
 '3',
 '1',
 '1운동',
 '운동',
 '건립',
 '대한민국임시정부',
 '임시',
 '정부',
 '법통',
 '불의',
 '항거']

In [21]:
hannanum.nouns(c[:66])

['대한민국헌법',
 '유구',
 '역사',
 '전통',
 '빛',
 '우리',
 '대한국민',
 '3·1운동',
 '건립',
 '대한민국임시정부',
 '법통',
 '불의',
 '항거한']

In [22]:
twitter.nouns(c[:66])

['대한민국',
 '헌법',
 '유구',
 '역사',
 '전통',
 '우리',
 '대한',
 '국민',
 '운동',
 '건립',
 '대한민국',
 '임시정부',
 '법',
 '통과',
 '불의',
 '항거']

In [23]:
kkma.morphs(c[:66])

['대한민국',
 '헌법',
 '유구',
 '하',
 'ㄴ',
 '역사',
 '와',
 '전통',
 '에',
 '빛나',
 '는',
 '우리',
 '대하',
 'ㄴ',
 '국민',
 '은',
 '3',
 '·',
 '1',
 '운동',
 '으로',
 '건립',
 '되',
 'ㄴ',
 '대한민국',
 '임시',
 '정부',
 '의',
 '법통',
 '과',
 '불의',
 '에',
 '항거',
 '하',
 'ㄴ']

In [24]:
hannanum.morphs(c[:66])

['대한민국헌법',
 '유구',
 '하',
 'ㄴ',
 '역사',
 '와',
 '전통',
 '에',
 '빛',
 '나는',
 '우리',
 '대한국민',
 '은',
 '3·1운동',
 '으로',
 '건립',
 '되',
 'ㄴ',
 '대한민국임시정부',
 '의',
 '법통',
 '과',
 '불의',
 '에',
 '항거한']

In [25]:
kkma.pos(c[:66])

[('대한민국', 'NNG'),
 ('헌법', 'NNG'),
 ('유구', 'NNG'),
 ('하', 'XSV'),
 ('ㄴ', 'ETD'),
 ('역사', 'NNG'),
 ('와', 'JC'),
 ('전통', 'NNG'),
 ('에', 'JKM'),
 ('빛나', 'VV'),
 ('는', 'ETD'),
 ('우리', 'NNM'),
 ('대하', 'VV'),
 ('ㄴ', 'ETD'),
 ('국민', 'NNG'),
 ('은', 'JX'),
 ('3', 'NR'),
 ('·', 'SP'),
 ('1', 'NR'),
 ('운동', 'NNG'),
 ('으로', 'JKM'),
 ('건립', 'NNG'),
 ('되', 'XSV'),
 ('ㄴ', 'ETD'),
 ('대한민국', 'NNG'),
 ('임시', 'NNG'),
 ('정부', 'NNG'),
 ('의', 'JKG'),
 ('법통', 'NNG'),
 ('과', 'JC'),
 ('불의', 'NNG'),
 ('에', 'JKM'),
 ('항거', 'NNG'),
 ('하', 'XSV'),
 ('ㄴ', 'ETD')]

In [26]:
hannanum.pos(c[:66])

[('대한민국헌법', 'N'),
 ('유구', 'N'),
 ('하', 'X'),
 ('ㄴ', 'E'),
 ('역사', 'N'),
 ('와', 'J'),
 ('전통', 'N'),
 ('에', 'J'),
 ('빛', 'N'),
 ('나는', 'J'),
 ('우리', 'N'),
 ('대한국민', 'N'),
 ('은', 'J'),
 ('3·1운동', 'N'),
 ('으로', 'J'),
 ('건립', 'N'),
 ('되', 'X'),
 ('ㄴ', 'E'),
 ('대한민국임시정부', 'N'),
 ('의', 'J'),
 ('법통', 'N'),
 ('과', 'J'),
 ('불의', 'N'),
 ('에', 'J'),
 ('항거한', 'N')]

In [27]:
twitter.pos(c[:66])

[('대한민국', 'Noun'),
 ('헌법', 'Noun'),
 ('유구', 'Noun'),
 ('한', 'Josa'),
 ('역사', 'Noun'),
 ('와', 'Josa'),
 ('전통', 'Noun'),
 ('에', 'Josa'),
 ('빛나는', 'Verb'),
 ('우리', 'Noun'),
 ('대한', 'Noun'),
 ('국민', 'Noun'),
 ('은', 'Josa'),
 ('3', 'Number'),
 ('·', 'Foreign'),
 ('1', 'Number'),
 ('운동', 'Noun'),
 ('으로', 'Josa'),
 ('건립', 'Noun'),
 ('된', 'Verb'),
 ('대한민국', 'Noun'),
 ('임시정부', 'Noun'),
 ('의', 'Josa'),
 ('법', 'Noun'),
 ('통과', 'Noun'),
 ('불의', 'Noun'),
 ('에', 'Josa'),
 ('항거', 'Noun'),
 ('한', 'Josa')]

# Scikit-Learn의 문서 전처리 기능

### BOW
- 몇번나왔냐 / 나왔냐 안나왔냐

### Scikit-Learn 의 문서 전처리 기능

##### DictVectorizer
- 안써!
- 내가 토큰도 만들고 카운팅도하고 해서 dic에 줘야함
- 이것이 voca를 만듦
- 기능이 별거 없어서 거이안씀

##### CountVectorizer
- 이걸 써!
- 1 문서를 tokenizing
- 2 토큰의 사용 횟수를 세줌
- 3 BOW 인코딩
- 만들어진 voca는 dictionary로 저장이 되있음
- 숫자는 컬럼의 순서
EX)
    - 10종류의 단어로 이루어져 있어서 벡터의 길이가 10
    - and는 없고 ....
- voca에 없는 단어를 하면 다 없다고 나옴
- copus전체를 pow인코딩
- 몇가지 인수

### Stop Words
- 토큰 만들때 이단어는 빼버려라
- 얘는 몇번 나왔는지 새봤자 의미가 없다 (the, a ....)
- english를 넣으면 자동을 의미없는 것들을 없에버림

### 토큰
- 스스로 토크나이징을 하면 nltk 같은 것들이 필요없냐? 아니!
- 얘는 형태소분석같은 작업은 못하고 기본적인 것만 가능
- 그래서 사용하는 것이 3가지 인수 = analyzer, tokenizer, token_pattern
- 토큰이 되는 것 의 조건을 걸어줄수 있음

### n-그램
- 복합명사의 ...(?)
- 단어 하나짜리 단어만 토큰으로 사용! (오타가 있었음)
- ngram_range=(1, 2) : 한 단어와 붙어있는 두 단어도 토큰으로 인정

### 빈도수
- 문서에서 토큰이 너무 많이 나타나거나 적게 나타나는 애들은 영양가가 없다라고 판단
- 4번 나타난것은! 1번 나타난것은! = 영양가가 없다

### TF-IDF
- bow방식에서 얘기 하던 숫자 = 이단어가 몇번나왔냐
- tf = 그 단어를 포함하고 있는 document의 수
    - ex) a 라는 단어는 모든 document가 가지고 있으니깐 영양가가 없다
    - 그래서 역으로...
- idf = 전체의 문서의 수에서 그문서를 포함하고 있는 문서의 수를 나눔
    - 사람마다 정의가 조금 다른데 여기서는 이렇게...
- 여러문서에 있는 단어들은 가중치가 작아짐
- 나중에 분석할때 별 영양가가 없음

### Hashing Trick
- ex) doc의 수가 11314임 하나의 길이는 게시판에 하나올리는 길이
- CountVectorizer()로 세보면 <문서의갯수 * 단어의수>
- 이것 자체로 굉장한 메모리를 차지하는데 그것보다 찾는 속도가 너무느림

`플러스 지식`
- zip's Law : 제일 많이나온 것에 반 = 두번째 많이 나온 것  의 반= 세번째많이

# 나이브 베이즈 분류 모형

### 나이브 가정
- 조건부 독립 (y가 k 번째 클래스에서만 독립)
- 실제로 많이 성립이 됨
- y값이 클래스가 결정되면 이때는 x1, x2 ... 들이 무조건 조건부 독립
- 위같은 인과 관계를 생각하면 성립되는 가정임
- P(y = C_k)는 pi안에 있는 것이 아님 주의하세요

### 가우시안 정규 분포 Liklihood 모형
- 모두 가우시안 일 경우
- 각각의 x에 대한 확률변수 수식
- 수식이라는 것은 mu 와 시그마를 알게되면 함수를 알게됨!
- 그럼 mu와 시그마 제곱은 어떻게 구해?
- 클래스가 k인 것들만 모아서 xd인 것들만 모아와 어떻게? in 노트

### 베르누이 분포 Liklihood 모형
- 모두 0,1만 나올 경우

### 다항 분포 LIklihood 모형
- 앞에거랑 조금 다른데 앞에거는 숫자하나당 하나의 확률변수로 생각
- 여기서는 x 는 하나의 벡터x이다 그런데 다항분포에서 나왔음
- 차원 전체를 하나의 확률 변수로 봄

### Scikit-Learn에서 제공하는 나이브 베이즈 모형
##### 사전 확률과 관련된 속성
- 위 세가지로 구현이 되어있음
- 이것을 가지고 fit을 하면 속성들이 생김
    - clsses_ 라벨 종류
    - class_count_ 1이 몇개있고 2가 몇개있고 등....
        - 사전 확률(P(y))을 구할때 사용!  X가 뭔지보여주지않고 y를 알아맞춰봐!
    - class_prior_ 사전확률
    
##### Likelihood 추정 속성
- clss별로 니깐 theta_, sigma_ 둘다 matrix
- 각각의 면이 나온 횟수를 다 세줘야함
    - theta구할때 분자로 쓰임
    - 전체던진 횟수로 나누어주면 theta값이 나오는 거임
- 지수함수에 넣어줘서 바꿔야함

##### 스무딩
- 이따가 데이터를 직접 보여주면서!

### 가우시안 정규 분포 나이브 베이즈 모형
- 0,1 두종류의 클래스 x1, x2두가지 X
- mu값이 당연히 다르고 cov-matrix도 다름 (어느쪽을 향하는지)
- 나이브베이즈로 푼다! 는 시그마의 대각 성분이 모두 0이다 라고 생각
- predict_proba = 0일확률과 1일확률 둘다 알려줌
- prod()는 곱하기! 이걸왜 썼냐면 변수끼리 독립이기 때문에 joint를 구할려면 곱하면 끝

In [32]:
np.random.seed(0)
rv0 = sp.stats.multivariate_normal([-2, -2], [[1, 0.9], [0.9, 2]])
rv1 = sp.stats.multivariate_normal([2, 2], [[1.2, -0.8], [-0.8, 2]])
X0 = rv0.rvs(40)
X1 = rv1.rvs(60)
rv0

In [33]:
from sklearn import datasets
iris = datasets.load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
X.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [34]:
y = pd.DataFrame(iris.target, dtype="category", columns=["species"])
y = y["species"].cat.rename_categories(iris.target_names)
y.tail()

145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [35]:
from sklearn.naive_bayes import GaussianNB
model_norm = GaussianNB().fit(X, y)

In [47]:
pred = model_norm.predict(X)

In [45]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]], dtype=int64)

In [46]:
from sklearn.metrics import classification_report
print(classification_report(y, pred))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        50
 versicolor       0.94      0.94      0.94        50
  virginica       0.94      0.94      0.94        50

avg / total       0.96      0.96      0.96       150



### 베르누이 분포 나이브 베이즈 모형
- X 의 값이 0 아니면 1인 놈들 (y가 아니야)
- 여기는 log가 취해져있어서 우리가 볼때는 exp를 해줌
- fc는 스무딩하기 이전의 값들
- alpha는 default로 1 (값이 클수록 fair한 동전으로 다가감)

##### 스무딩
- in 노트

In [123]:
from sklearn.datasets import load_digits
from sklearn.preprocessing import Binarizer
from sklearn.naive_bayes import BernoulliNB

In [124]:
digits = load_digits()

In [77]:
binar = Binarizer(threshold=8).fit(digits.data)

In [78]:
binar

Binarizer(copy=True, threshold=8)

In [79]:
data = binar.transform(digits.data)

In [80]:
data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]])

In [81]:
model_bern = BernoulliNB().fit(data, digits.target)

In [83]:
pred = model_bern.predict(digits.data)

In [84]:
confusion_matrix(digits.target, pred)

array([[158,   0,   0,   0,  14,   1,   0,   0,   1,   4],
       [  0,  67,  18,   0,  12,   1,   0,   2,  67,  15],
       [  0,   5, 154,   1,   2,   0,   0,   2,  11,   2],
       [  0,   0,   3, 125,   0,   3,   0,   2,  19,  31],
       [  0,   0,   0,   0, 175,   0,   0,   3,   3,   0],
       [  0,   0,   0,   0,   1, 156,   0,   0,   2,  23],
       [  0,   6,   4,   0,   6,  16, 146,   0,   3,   0],
       [  0,   0,   0,   0,   6,   2,   0, 171,   0,   0],
       [  0,   6,   4,   0,   1,   3,   0,   5, 139,  16],
       [  0,   1,   1,   1,   7,   2,   0,   9,   6, 153]], dtype=int64)

In [91]:
print(classification_report(digits.target, pred))

             precision    recall  f1-score   support

          0       1.00      0.89      0.94       178
          1       0.79      0.37      0.50       182
          2       0.84      0.87      0.85       177
          3       0.98      0.68      0.81       183
          4       0.78      0.97      0.86       181
          5       0.85      0.86      0.85       182
          6       1.00      0.81      0.89       181
          7       0.88      0.96      0.92       179
          8       0.55      0.80      0.65       174
          9       0.63      0.85      0.72       180

avg / total       0.83      0.80      0.80      1797



In [122]:
theta = np.exp(model_bern.feature_log_prob_)
theta[0].resh

array([0.00555556, 0.01666667, 0.88888889, 0.99444444, 0.98888889,
       0.76111111, 0.03888889, 0.00555556, 0.00555556, 0.35      ,
       0.98888889, 0.99444444, 0.98888889, 0.99444444, 0.32777778,
       0.00555556, 0.00555556, 0.85      , 0.99444444, 0.80555556,
       0.52777778, 0.98888889, 0.8       , 0.00555556, 0.00555556,
       0.95555556, 0.99444444, 0.38888889, 0.07777778, 0.98888889,
       0.97777778, 0.00555556, 0.00555556, 0.97777778, 0.99444444,
       0.21666667, 0.02777778, 0.99444444, 0.96666667, 0.00555556,
       0.00555556, 0.89444444, 0.99444444, 0.42222222, 0.4       ,
       0.99444444, 0.9       , 0.00555556, 0.00555556, 0.36666667,
       0.99444444, 0.99444444, 0.97222222, 0.99444444, 0.61111111,
       0.00555556, 0.00555556, 0.01111111, 0.91666667, 0.99444444,
       0.99444444, 0.9       , 0.13333333, 0.00555556])

In [88]:
model_bern2 = BernoulliNB().fit(digits.data, digits.target)

In [89]:
pred2 = model_bern2.predict(digits.data)

In [90]:
confusion_matrix(digits.target, pred2)

array([[175,   1,   0,   0,   2,   0,   0,   0,   0,   0],
       [  0, 112,  21,   0,   3,   1,   1,   1,  32,  11],
       [  0,   6, 153,   6,   0,   0,   0,   1,  11,   0],
       [  1,   1,   3, 157,   0,   2,   0,   3,   7,   9],
       [  0,   1,   0,   0, 172,   0,   0,   7,   1,   0],
       [  2,   3,   0,   2,   1, 149,   2,   0,   3,  20],
       [  0,   5,   0,   0,   2,   2, 171,   0,   1,   0],
       [  0,   0,   0,   0,   3,   0,   0, 175,   1,   0],
       [  0,  13,   1,   4,   0,   3,   2,   2, 142,   7],
       [  0,   6,   0,   3,   7,   3,   0,   9,   6, 146]], dtype=int64)

In [92]:
print(classification_report(digits.target, pred2))

             precision    recall  f1-score   support

          0       0.98      0.98      0.98       178
          1       0.76      0.62      0.68       182
          2       0.86      0.86      0.86       177
          3       0.91      0.86      0.88       183
          4       0.91      0.95      0.93       181
          5       0.93      0.82      0.87       182
          6       0.97      0.94      0.96       181
          7       0.88      0.98      0.93       179
          8       0.70      0.82      0.75       174
          9       0.76      0.81      0.78       180

avg / total       0.87      0.86      0.86      1797



### 다항 분포 나이브 베이즈 모형
- text분석에서 쓸수있음
- 텍스트가 짧을 때는 나왔냐 안나왔냐...
- 텍스트가 길때는 어떤단어가 얼마나 많이 나왔는가 분포의 비율이 중요
- 이때 멀티노미얼 나이브 베이즈
- 아까는 동전이 4개였는데 지금은 4면체 주사위 1개만 있으면 됨
- 주사위 2개 (클래스 0 일 때, 클래스 1 일 때)

In [127]:
from sklearn.naive_bayes import MultinomialNB
model_mult = MultinomialNB().fit(digits.data, digits.target)

In [128]:
pred_m = model_mult.predict(digits.data)
pred_m

array([0, 1, 1, ..., 8, 9, 8])

In [131]:
print(classification_report(digits.target, pred_m))

             precision    recall  f1-score   support

          0       0.99      0.98      0.99       178
          1       0.87      0.75      0.81       182
          2       0.90      0.90      0.90       177
          3       0.99      0.87      0.93       183
          4       0.96      0.96      0.96       181
          5       0.97      0.86      0.91       182
          6       0.98      0.97      0.98       181
          7       0.89      0.99      0.94       179
          8       0.78      0.89      0.83       174
          9       0.76      0.88      0.82       180

avg / total       0.91      0.91      0.91      1797



### 뉴스 그룹 분류

- pipline = 전처리하는 객체들을 모델링하는 객체와 이어붙임